# Application compose file for Mangrove Monitoring
# This is the dev compose file for dev and testing purposes, all containers run on a single Docker host on one network

services:  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8081:80
    environment:
      - REACT_APP_API_SERVER_URL=http://localhost:8000
    depends_on:
      - webserver
  
  # Make sure you have a .env file with env variables set for AWS secret credentials
  webserver:
    build: ./webserver
    container_name: webserver
    ports:
      - 8082:80
    depends_on:
      - db
    environment:
      - PORT=80
      - MONGO_CONNECTION_STRING=mongodb://mongo_db:27017/mmict-test
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - mmict_bridge
  
  db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db # named volume - name:path
    networks:
      - mmict_bridge

  ip-service:
    build: ./ip-service
    container_name: image_processing_service
    ports:
     - 8080:5000

  classification-service:
    build: ./classification-service
    container_name: classification_service
    ports:
     - 5001:5001

networks:
  mmict_bridge:


# need to do this for named volumes since can be used across multiple services
volumes:
  mongo-db: 